language: c++

dist: focal

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - qtbase5-dev
      - libkf5widgetsaddons-dev
      - libkf5kio-dev
      - libkf5solid-dev
      - libkf5auth-dev
      - libarchive-dev

before_install:
  - sudo apt-get -q update

script:
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build ./
